baseURL: "https://lapsedgeographer.london/"
title: The Lapsed Geographer
languageCode: "en-gb"
theme: "lapsedgeographer"
paginate: 10
summaryLength: 70

permalinks:
    post: "/:year-:month/:slug/"
    page: "/:contentbasename"

markup:
  markup.tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

outputFormats:
    outputFormats.RSS:
        baseName: "rss"

menu:
  links:
    - name: GitHub
      url: https://www.github.com/mattkerlogue
      weight: 100
    - name: Mastodon
      url: https://fosstodon.org/@mattkerlogue
      weight: 300
    - name: Bluesky
      url: https://bsky.app/profile/matt.kerlogue.co.uk
      weight: 200

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
    respectDoNotTrack: true
  instagram:
    disable: false
    simple: true
  vimeo:
    disable: false
    enableDNT: true
    simple: true
  x:
    disable: true
    enableDNT: true
    simple: true
  youTube:
    disable: false
    privacyEnhanced: true