baseURL: "https://lapsedgeographer.london/"
title: The Lapsed Geographer
languageCode: "en-gb"
theme: "lapsedgeographer"
paginate: 10
summaryLength: 70

permalinks:
    post: "/:year-:month/:slug/"
    page: "/:filename"

markup:
  markup.tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  highlight:
    noClasses: false

outputFormats:
    outputFormats.RSS:
        baseName: "rss"

menu:
  links:
    - name: GitHub
      url: https://www.github.com/mattkerlogue
      weight: 100
    - name: Mastodon
      url: https://fosstodon.org/@mattkerlogue
      weight: 200
    - name: Twitter
      url: https://twitter.com/mattkerlogue
      weight: 200

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true