baseURL = "https://lapsedgeographer.london/"
languageCode = "en-gb"
theme = "hugo-theme-terminal"
paginate = 10
googleAnalytics = "UA-163162822-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year-:month/:slug/"
    page = "/:filename"

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "The Lapsed Geographer"
    subtitle = ""
    keywords = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "The Lapsed Geographer"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "All posts"
        url = "/archive"
        weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputFormats]
    [outputFormats.RSS]
        baseName = "rss"